### ISSUE TITLE
Could you provide me with any subject-related information?

### ISSUE THREAD

**Issue by ayan221** [aiotgroup/XRF55-repo#6]
Firstly, I would like to express my gratitude for the XRF55 dataset, which has been incredibly valuable for our project. The dataset has significantly contributed to our research, and we appreciate the effort that has gone into making it available.

As we continue to work with the XRF55 dataset, we have noticed that some subject-related information, particularly regarding gender and potentially other relevant attributes, seems to be absent. We understand that this information might already exist in some form, or there may be valid reasons for its exclusion.

Request:
**Exploration of Gender Information**: If it is possible, we would greatly appreciate the inclusion of gender data for the subjects within the dataset. This additional information would enhance our analysis and allow us to achieve more nuanced results.
**Consideration of Other Subject-Related Attributes**: If there are any other subject-related attributes available that could be shared, we believe they would further enrich the dataset and its applications.

**Comment by aiotgroup** [comment]
Thank you for your question, the gender information for each subject in XRF55 dataset is shown below, where Volunteer_ID corresponds to the number before the first underscore of the file name. For example, 03_25_15.npy represents the data for volunteer 03.
![5e35f98692ed0bb9dd1d831797c4c7f](https://github.com/user-attachments/assets/bbaff68e-6815-4fd8-b517-7896a35b43aa)

**Comment by ayan221** [comment]
Thank you ! That's exactly what I needed.
